# -*- coding: utf-8 -*-
"""primeira_aula.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uf21QsksXYErIx64KW844w8GvFr6H4KD

# Bibliotecas
"""
import numpy
import pandas
import matplotlib.pyplot as plot

"""# Lendo os Dados"""

dataset_path = '../dataset/microdados_enem_2019.csv'

dataset = pandas.read_csv(dataset_path)

print(dataset.head())

print(dataset['SG_UF_RESIDENCIA'].unique())

"""# Desafio 1: Proporção de inscritos por idade"""

percentage_participants_per_age = dataset['NU_IDADE'].value_counts(normalize=True).sort_index() * 100
print(percentage_participants_per_age)

plot.pie(percentage_participants_per_age, labels=dataset['NU_IDADE'].unique())

plot.show()

"""# Desafio 2: De quais estados são os inscritos com 13 anos?"""

print(dataset.query('NU_IDADE == 13')['SG_UF_RESIDENCIA'])

"""# Desafio 3: Titulo no gráfico"""

plot.axes(dataset['NU_IDADE'].hist(bins=20))
plot.title('Participantes x Idade')
plot.show()

"""# Desafio 4: Plotar gráficos com o numero de treineiros e não treineiros"""

number_of_treineiros = dataset['IN_TREINEIRO'].value_counts(normalize=True) * 100

plot.pie(number_of_treineiros, labels=numpy.sort(dataset['IN_TREINEIRO'].unique()), autopct='%1.0f%%')

plot.show()

"""# Comparar as distribuições das provas em inglês e espanhol"""

english_test_grades = dataset.query('TP_LINGUA == 0')['NU_NOTA_LC']
spanish_test_grades = dataset.query('TP_LINGUA == 1')['NU_NOTA_LC']

languages_test_data = [english_test_grades, spanish_test_grades]

headers = ["Inglês", "Espanhol"]

languages_test_data = pandas.concat(languages_test_data, axis=1, keys=headers)

languages_test_data.plot.box(grid=True, figsize=(8, 6))
plot.show()

"""# Medidas de Localização"""

mean = dataset['NU_NOTA_REDACAO'].mean()
median = dataset['NU_NOTA_REDACAO'].median()
standard_deviation = dataset['NU_NOTA_REDACAO'].std()
quantile = dataset['NU_NOTA_REDACAO'].quantile(0.75)

print(f'Média: {mean}, Mediana: {median}, Desvio Padrão: {standard_deviation}, Terceiro Percentil(75%): {quantile}')

tests = ['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_MT', 'NU_NOTA_LC', 'NU_NOTA_REDACAO']

print(dataset[tests].describe())

dataset[tests].plot.box(grid=True, figsize=(8, 6))
plot.title('Distribuição das Notas')
plot.show()
